version: '3.7'
services:
  postgres:
    image: postgres:10.4
    container_name: tigercat_postgres
    ports:
      - '35432:5432'
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    links:
      - postgres
    depends_on:
      - postgres
    container_name: tigercat_server
    ports:
      - '4000:4000'
    environment:
        PORT: 4000
    build:
      context: server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
      - /app/prisma

  client:
    container_name: tigercat_client
    ports:
      - '3000:3000'
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
      - /app/.next

volumes:
  postgres-data: